from pydantic import BaseModel, Field
from typing import List, Optional

class QueryRequest(BaseModel):
    ticket: str = Field(..., description="Customer problem description in Arabic/English", example="النت فاصل عندي ولمبة DSL بتنور وتطفي")

class RetrievedDoc(BaseModel):
    content: str
    score: Optional[float] = None

class QueryResponse(BaseModel):
    ticket: str = Field(..., description="Original customer query")
    response: str = Field(..., description="Generated Arabic AI response")
    sources_count: int = Field(..., ge=0, description="Number of context chunks retrieved from FAISS")
    execution_time_seconds: float = Field(..., description="Latency in seconds")
    prompt_tokens: int = Field(0, description="Input tokens sent to LLM")
    completion_tokens: int = Field(0, description="Output tokens generated by LLM")
    total_tokens: int = Field(0, description="Total tokens consumed")

class IngestRequest(BaseModel):
    file_path: Optional[str] = Field(None, description="Custom document path (optional)")

class IngestResponse(BaseModel):
    message: str = Field(..., description="Human-readable confirmation message")
    chunks_indexed: int = Field(..., ge=0, description="Number of chunks successfully indexed")
    index_path: str = Field(..., description="Path to the FAISS index file")